[advisories]
ignore = [
]

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "0BSD",
    "OpenSSL",
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]

[licenses.private]
ignore = true

[bans]
multiple-versions = "warn"
wildcards = "deny"
deny = [
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"

[sources.allow-org]
#github = ["M4SS-Code"]
