name: CI

on: [push, pull_request]

permissions:
  contents: read

jobs:
  cargo-deny:
    name: cargo-deny
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v2

  fmt:
    name: rustfmt / 1.90.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.90.0
        with:
          components: rustfmt

      - name: Rust rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: clippy / 1.90.0
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.90.0
        with:
          components: clippy

      - name: Run clippy
        run: cargo clippy --all-features -- -D warnings

  cargo-hack:
    name: cargo-hack / 1.90.0
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@1.90.0

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-hack@0.6.37

      - name: Run cargo-hack
        run: cargo hack check --feature-powerset --no-dev-deps --at-least-one-of aws-lc-rs,ring --at-least-one-of rand,getrandom

  test:
    name: test / ${{ matrix.name }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - name: stable
            rust: stable
          - name: beta
            rust: beta
          - name: nightly
            rust: nightly
          - name: 1.85.0
            rust: 1.85.0

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Run tests
        run: cargo test

      - name: Run tests (--features websocket,portable-atomic)
        run: cargo test --features websocket,portable-atomic

      - name: Run tests (--no-default-features --features ring,getrandom)
        run: cargo test --no-default-features --features ring,getrandom
